books_for_database = (
    ("Dune", "Frank Herbert"),
    ("The Hitchhiker's Guide to the Galaxy", "Douglas Adams"),
    ("Neuromancer", "William Gibson"),
    ("Foundation", "Isaac Asimov"),
    ("1984", "George Orwell"),
    ("Brave New World", "Aldous Huxley"),
    ("The War of the Worlds", "H.G. Wells"),
    ("Snow Crash", "Neal Stephenson"),
    ("The Martian Chronicles", "Ray Bradbury"),
    ("Ender's Game", "Orson Scott Card"),
    ("The Hobbit", "J.R.R. Tolkien"),
    ("A Game of Thrones", "George R.R. Martin"),
    ("Harry Potter and the Philosopher's Stone", "J.K. Rowling"),
    ("The Name of the Wind", "Patrick Rothfuss"),
    ("The Lion, the Witch and the Wardrobe", "C.S. Lewis"),
    ("Mistborn: The Final Empire", "Brandon Sanderson"),
    ("The Fellowship of the Ring", "J.R.R. Tolkien"),
    ("The Way of Kings", "Brandon Sanderson"),
    ("The Blade Itself", "Joe Abercrombie"),
    ("American Gods", "Neil Gaiman"),
    ("Dracula", "Bram Stoker"),
    ("Frankenstein", "Mary Shelley"),
    ("The Shining", "Stephen King"),
    ("It", "Stephen King"),
    ("The Haunting of Hill House", "Shirley Jackson"),
    ("The Exorcist", "William Peter Blatty"),
    ("Pet Sematary", "Stephen King"),
    ("The Silence of the Lambs", "Thomas Harris"),
    ("The Call of Cthulhu", "H.P. Lovecraft"),
    ("Interview with the Vampire", "Anne Rice"),
    ("Pride and Prejudice", "Jane Austen"),
    ("Jane Eyre", "Charlotte Brontë"),
    ("Romeo and Juliet", "William Shakespeare"),
    ("Gone with the Wind", "Margaret Mitchell"),
    ("Wuthering Heights", "Emily Brontë"),
    ("The Notebook", "Nicholas Sparks"),
    ("Outlander", "Diana Gabaldon"),
    ("The Fault in Our Stars", "John Green"),
    ("Emma", "Jane Austen"),
    ("A Walk to Remember", "Nicholas Sparks"),
    ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle"),
    ("And Then There Were None", "Agatha Christie"),
    ("The Da Vinci Code", "Dan Brown"),
    ("Gone Girl", "Gillian Flynn"),
    ("The Girl with the Dragon Tattoo", "Stieg Larsson"),
    ("Murder on the Orient Express", "Agatha Christie"),
    ("The Hound of the Baskervilles", "Arthur Conan Doyle"),
    ("The Girl on the Train", "Paula Hawkins"),
    ("In the Woods", "Tana French"),
    ("The Secret History", "Donna Tartt"),
    ("The Godfather", "Mario Puzo"),
    ("The Silence of the Lambs", "Thomas Harris"),
    ("The Girl with the Dragon Tattoo", "Stieg Larsson"),
    ("The Maltese Falcon", "Dashiell Hammett"),
    ("Mystic River", "Dennis Lehane"),
    ("The Big Sleep", "Raymond Chandler"),
    ("Red Dragon", "Thomas Harris"),
    ("Presumed Innocent", "Scott Turow"),
    ("The Talented Mr. Ripley", "Patricia Highsmith"),
    ("The Postman Always Rings Twice", "James M. Cain"),
    ("The Hunger Games", "Suzanne Collins"),
    ("Harry Potter and the Philosopher's Stone", "J.K. Rowling"),
    ("The Fault in Our Stars", "John Green"),
    ("Twilight", "Stephenie Meyer"),
    ("The Giver", "Lois Lowry"),
    ("To Kill a Mockingbird", "Harper Lee"),
    ("The Perks of Being a Wallflower", "Stephen Chbosky"),
    ("The Maze Runner", "James Dashner"),
    ("Divergent", "Veronica Roth"),
    ("The Lightning Thief", "Rick Riordan"),
    ("1984", "George Orwell"),
    ("Brave New World", "Aldous Huxley"),
    ("The Handmaid's Tale", "Margaret Atwood"),
    ("Fahrenheit 451", "Ray Bradbury"),
    ("The Hunger Games", "Suzanne Collins"),
    ("Animal Farm", "George Orwell"),
    ("Never Let Me Go", "Kazuo Ishiguro"),
    ("The Road", "Cormac McCarthy"),
    ("Station Eleven", "Emily St. John Mandel"),
    ("The Stand", "Stephen King"),
    ("The Adventures of Huckleberry Finn", "Mark Twain"),
    ("Treasure Island", "Robert Louis Stevenson"),
    ("The Count of Monte Cristo", "Alexandre Dumas"),
    ("Jurassic Park", "Michael Crichton"),
    ("The Three Musketeers", "Alexandre Dumas"),
    ("The Hunt for Red October", "Tom Clancy"),
    ("The Bourne Identity", "Robert Ludlum"),
    ("The Odyssey", "Homer"),
    ("20,000 Leagues Under the Sea", "Jules Verne"),
    ("The Call of the Wild", "Jack London"),
    ("Watchmen", "Alan Moore"),
    ("Maus", "Art Spiegelman"),
    ("The Sandman", "Neil Gaiman"),
    ("Persepolis", "Marjane Satrapi"),
    ("V for Vendetta", "Alan Moore"),
    ("Batman: The Dark Knight Returns", "Frank Miller"),
    ("Saga", "Brian K. Vaughan"),
    ("Preacher", "Garth Ennis"),
    ("The Walking Dead", "Robert Kirkman"),
    ("Y: The Last Man", "Brian K. Vaughan"),
)