# Generated by Django 5.0.2 on 2024-03-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_booksinbookcase_bookcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksinbookcase',
            old_name='bookcase',
            new_name='user_bookcase',
        ),
    ]
