# Generated by Django 5.0.2 on 2024-03-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_bookcase_booksinbookcase_user_bookcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksinbookcase',
            old_name='user_bookcase',
            new_name='bookcase',
        ),
    ]
